### ISSUE TITLE
add_callback issue. 

### ISSUE THREAD

**Issue by poqudrof** [Luos-io/Pyluos#15]
Hello, 

I have a request and issue on the callbacks. 

I cannot remove the callbacks I created :[ . I can add it and remove it directly. But I can't remove an old callback.

This works:
``` python
def activated(event):
    print(event)
    
button.add_callback("pressed",activated)
button.remove_callback("pressed",activated)
``` 

This does not: 
``` python
def activated(event):
    print(event)
    
button.add_callback("pressed",activated)

## in interpreter   (activated is accessible in the interpreter)
>> button.remove_callback("pressed",activated)
``` 

Also, is it useful to have two callbacks for the same event ? My initial guess was that the new event would replace the previous one. 

Cheers, 
Jeremy.

**Comment by pierre-rouanet** [comment]
I'm not sure to understand the difference between the two versions of your example. Using callbacks in interactive mode or in a script should not make any difference.

What I can think of is that you actually redefined the activated function and thus when you want to remove it as a callback it's not found anymore (it's not the same function). Is that right?

>Also, is it useful to have two callbacks for the same event ? My initial guess was that the new event would replace the previous one.

Yes I guess you are right. Having multiple callbacks on the same event could be useful in complex setup but at the moment it's probably not worth the API complexity. We could imagine something like:

```python
button.callbacks['pressed'] = activated
button.callbacks['pressed'] = eraseWithAnotherFunction
del button.callbacks['pressed']
```

Would this feel clearer?

**Comment by poqudrof** [comment]
Ok I see why,  was not sure what happened to the function when we redefine it. 

Just one event will be much clearer, and it is not that hard to create a method to extend the previous callback to add event after or before the exsiting one. 
Thanks :)
