### ISSUE TITLE
How to send a command

### ISSUE THREAD

**Issue by poqudrof** [Luos-io/Pyluos#17]
Hello, 

On main Readme you propose to send data to Robus. I cannot manage to send values to my module (motor position). 

Here is my message:  
> {"modules":{"gloo_servo":{"target_position":-30}}}

The code can be generated and sent to an USB module with this: 

``` ruby 
require 'rubygems'
require 'rubyserial'
require 'json'

connection = Serial.new '/dev/ttyACM0', 57600
message = { "modules" =>  { "gloo_servo" => { "target_position" => -20 } }}
puts connection.write message.to_json
``` 
As we get an output (amount of data written) it seems that the message is send properly.

Is there an easy way to print out the Python messages for debug ?

## EDIT: 

I just found out that I must add a  "\r" at the end of the command. 

``` ruby 
require 'rubygems'
require 'rubyserial'
require 'json'

connection = Serial.new '/dev/ttyACM0', 57600
message = { "modules" =>  { "gloo_servo" => { "target_position" => 40 } }}
puts connection.write(message.to_json + "\r")
``` 
It works   \o/ 

To test this you need to install ruby or Jruby and the gem `rubyserial`. 

Cheers, 
Jeremy.

**Comment by pierre-rouanet** [comment]
>I just found out that I must add a "\r" at the end of the command.

Yet at the moment we need to add this \r at the end of the message on USB (not on WiFi). It'll probably be removed at some point though. I'll add it to the documentation, thanks! 

>Is there an easy way to print out the Python messages for debug ?

Not yet but this will be added in #11.
