### ISSUE TITLE
Enabling speed mode and setting target_rot_speed at once seems broken

### ISSUE THREAD

**Issue by pierre-rouanet** [Luos-io/Pyluos#53]
Hi LuosTeam!

When using a _ControlledMotor_ it seems that setting at the same time, meaning sent from pyluos in one message both the _rot_speed_mode_ to True and setting a _target_rot_speed_, the _target_rot_speed_ is not actually set.

* When sending _{'disk_top': {'parameters': 153, 'target_rot_speed': 100}_ --> not working
* _{'disk_top': {'parameters': 153}_ then _{'disk_top': {'target_rot_speed': 100}_ --> working as intended.

**Comment by nicolas-rabault** [comment]
Pyluos was just trying to do smart things but that was not so smart...
