### ISSUE TITLE
Setting a target_rot_speed turn the compliance off on AX motors

### ISSUE THREAD

**Issue by pierre-rouanet** [Luos-io/Pyluos#59]
When setting a target_rot_speed on MX motors, it does indeed change the maximum speed (called moving_speed in dynamixel world) and does not change the compliancy.

When doing the same operation on a AX motors, it turn the motor stiff for no reason.

From what I've seen on dynamixel registers, writing moving_speed should be the same for AX and MX motors though.

**Comment by nicolas-rabault** [comment]
It's not a bug it's a feature from dynamixel...
