### ISSUE TITLE
have access to Luos version from pyluos

### ISSUE THREAD

**Issue by AntoineVenier** [Luos-io/Pyluos#77]

**Comment by fleborne** [comment]
Also, module `pyluos` has no attribute `__version__`. It could be useful to access pyluos version programmatically, especially if pyluos was not installed with pip.

**Comment by nicolas-rabault** [comment]
To access Luos revision of a container from pyluos you can do : 
``` python
device.container.luos_revision
```
You also can access to your container revision : 
```python
device.container.firmware_revision
```
I think we forgot to close this issue.
