### ISSUE TITLE
[BUG] Device() became blocking

### ISSUE THREAD

**Issue by fleborne** [Luos-io/Pyluos#87]
**Describe the bug**
Calling `Device("COM3")` doesn't return (blocking behavior) on PyLuos 1.3.0.

**Network configuration**
The gate is plug to the computer using a USB cable; nothing is plugged to the gate.

**How to reproduce the bug**
Plug the gate, and run the following using pyluos 1.3.0

```
from pyluos import Device
d = Device('COM3')
```

**Additional context**
It works on both versions 1.2.3 and 1.2.4, but not on 1.3.0

**Comment by nicolas-rabault** [comment]
In the 1.0.0 release of Luos we simplify the routing table. This new routing table format become incompatible with 1.2.x revision of pyluos and reverse.
If you update your boards into 1.0.0 you should be able to use 1.3.0 revision of pyluos.
I will look at a way to display something on pyluos about that.
Thank you for reporting.
