### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by wisehackermonkey** [Luos-io/Pyluos#91]
**Describe the bug**

Trying to run reachy package from jupyter notebook, im trying to connect to the reachy simulator here [Pollen Robotics Playground](http://playground.pollen-robotics.com/#quickstart)  

![image](https://user-images.githubusercontent.com/29699356/104794453-854dac80-575c-11eb-95b2-55d398374eb7.png)

## the error 
![image](https://user-images.githubusercontent.com/29699356/104794479-b0d09700-575c-11eb-9c1d-79e40677cadb.png)

**How to reproduce the bug**
Run the docker container with 

**Additional context**
Im running the docker container on windows 10 education 
ekkus93/reachy-docker:latest
```docker
version: '3'

services:
    reachy-docker:
        image: ekkus93/reachy-docker:latest
        container_name: reachy-docker
        ports:
            - 8888:8888
            - 8889:8889
            - 8890:8890
            - 9000:9000
            - 6171:6171
            - 843:843
            - 7189:3389
            - 7183:1883
        volumes:
            - ../../../reachy:/reachy
        stdin_open: true
        tty: true

```
docker file
```docker
FROM ubuntu:18.04
LABEL maintainer="phillipcchin@gmail.com"

RUN apt-get update && apt-get upgrade -y
RUN apt-get install wget screen bzip2 curl -y

RUN apt-get install build-essential -y
RUN apt-get install emacs -y

RUN apt-get install libpulse-dev libasound2-dev pavucontrol -y

# Anaconda
# COPY ./Anaconda3-2020.07-Linux-x86_64.sh /tmp/
RUN curl https://repo.anaconda.com/archive/Anaconda3-2020.07-Linux-x86_64.sh -s -o /tmp/Anaconda3-2020.07-Linux-x86_64.sh
RUN cd /tmp && bash ./Anaconda3-2020.07-Linux-x86_64.sh -b -p /opt/anaconda && rm Anaconda3-2020.07-Linux-x86_64.sh
RUN /opt/anaconda/bin/conda update -n base conda
RUN /opt/anaconda/bin/conda install pip
RUN /opt/anaconda/bin/pip install --upgrade pip

COPY environment.yml /tmp
RUN cd /tmp && /opt/anaconda/bin/conda env create -f environment.yml && rm environment.yml
ENV PATH /opt/anaconda/bin:$PATH

SHELL ["/bin/bash", "-c"]

RUN echo "source activate reachy-docker" >> ~root/.bashrc

ENV TERM xterm-256color
VOLUME ["/reachy"]

COPY ./run.sh /tmp
RUN chmod ugo+x /tmp/run.sh
CMD ["/tmp/run.sh"]
```

**Comment by nicolas-rabault** [comment]
Hi @wisehackermonkey,
It seems that the Reachy package is not up to date with the latest revision of pyluos.
`module` have been changed to `container` since 1.3.0 revision of pyluos.
You should ask Pollen about the good revision of pyluos to use with Reachy.
@pierre-rouanet, @matthieu-lapeyre

**Comment by pierre-rouanet** [comment]
See https://github.com/pollen-robotics/reachy/issues/67

**Comment by wisehackermonkey** [comment]
@nicolas-rabault thanks!
@pierre-rouanet

**Comment by wisehackermonkey** [comment]
@pierre-rouanet @nicolas-rabault 
IT WORKED! Thanks!
![image](https://user-images.githubusercontent.com/29699356/105269052-113e4a80-5b48-11eb-8288-d6fb53df7c08.png)

```bash
 pip install reachy==1.3.2
```
