### ISSUE TITLE
[BUG] Cannot get data with device._poll_once() function

### ISSUE THREAD

**Issue by assembly-lab** [Luos-io/Pyluos#94]
**Describe the bug**
I'm using pyluos to send and receive messages to / from a luos network. I don't have any problem to send messages to a particular node but I fail to receive messages from the network with the function _poll_once().

I created a branch "bootloader" in Pyluos in wich I placed a pyluos/tools/bootloader.py script. In this script I send messages to the network and I'm waiting for responses from it. I can see the response with a print(self._state) in _poll_once() but I don't see it in luos_flash().
See prints here: https://github.com/Luos-io/Pyluos/commit/4a0efbe19085b8f8c4a5463a17d16374cd3439a3

**Network configuration**
- I have 2 nodes : a gate and a node flashed with the luos bootloader.

**How to reproduce the bug**
Launch "tools/bootloader.py flash" and notice that the json response is printed in _poll_once() but not in luos_flash().

Here is a capture of the console when I launch the script :
<img width="277" alt="issue_pyluos" src="https://user-images.githubusercontent.com/23093028/117845533-f0c60780-b280-11eb-893a-155581b2f7fb.png">

The response is trigged in _poll_once() but not in luos_flash().

**Comment by JeromeGalan** [comment]
@ncros3  and @nicolas-rabault : what about this ?
