### ISSUE TITLE
[BUG]  Pyluos doesn't open symlinked ports.

### ISSUE THREAD

**Issue by fleborne** [Luos-io/Pyluos#96]
**Describe the bug**
Pyluos doesn't open symlinked ports.

**How to reproduce the bug**
Use a udev rule that creates a symlink for a gate :
```
SUBSYSTEM=="tty", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6015", GROUP="dialout", MODE="0666", RUN+="echo USB CONNECTED!", SYMLINK+="luos-gate"
```
and using ipython for instance, do the following:

```python
from pyluos import Device
d = Device("/dev/luos-gate")
```

will return

```
ValueError: No corresponding IO found (among <function discover_hosts at 0x7f199e102f70>).
```

**Additional context**
It looks like the issue come from the io to host conversion but I haven't found the exact reason yet.

**Comment by fleborne** [comment]
I found the problem, I'm preparing a PR...

**Comment by fleborne** [comment]
I think this issue can be closed now?

**Comment by JeromeGalan** [comment]
Thanks for your contribution ;-)
